### ISSUE TITLE
AYS run drops some actions

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#563]
To reproduce:

1. define a `test` actor with two actions:
    ```
    def t1(job):
        pass

    def t2(job):
        pass
    ```

2. in your blueprint, add:
    ```
    test__demo:

    actions:
       - action: 't2'
         actor: test
       - action: 't1'
         actor: test

    ```

3. do `ays blueprint; ays run`
4. check run: action `t2` doesn't show up
