### ISSUE TITLE
Drop HRD for AYS actor templates schema

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#565]
We are progressively removing HRD from JumpScale but the schema definition of AYS actor templates is still written using HRD.

I think we have two options here: 
1. Replace HRD with yaml. yaml is now used +- everywhere in JumpScale for configuration. Then writting some code to convert yaml schema to capnp schema.
2. Immediately writing actor template schema in capnp format. But then we need to find a solution for the metadata that come with a schema ( consumer, parent, description, default values)

**Comment by despiegk** [comment]
lets make sure we keep it simple, how would yaml file look like?

**Comment by despiegk** [comment]
any ideas how indeed we can add info to capnp? or should that be separate yaml file?

**Comment by zaibon** [comment]
Example yaml file for schema definition could be:
```yaml
attributes:
    - name: 'ip'
      type: 'string'
      regex: ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$
      required: true

    - name : 'ports'
      list: true
      type: 'int'
      required: false

    - name: 'os'
      parent: 'os.ssh'

    - name: 'producer1'
      consume: 'producer'
      min: 1
      max: 5
```

I don't have a solution to to include these metadata in capnp directly yet. so inded maybe a yaml file next to it. but that's not really more user friendly
