### ISSUE TITLE
mvp-cockpit: vdc service is created even when location attribute was not specified

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#591]
Tested on Cockpit for Artilium:
- [Cockpit VM](https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=3856)
- [Cockpit Portal](https://artilium.aydo2.com/ays81/ays81/Services?ayspath=/optvar/cockpit_repos/yves04)

Steps:
1. Start with a new repository, for example yves04
2. First create faulty blueprint, forgetting to mention the location for the new VDC:
```
g8client__cl:
  url: gig.demo.greenitglobe.com
  login: artiliumadmin
  password: artilium12345
  account: Artilium Account
vdc__vdc4yves04:
  g8client: cl
  account: Artilium Account
actions:
  - action: install
     actor: vdc
     service: vdc4yves04
```
3. execute the blueprint:
```
ays blueprint
```

=> as expected, you get an error about the missing location:

```
JSExceptions.Input: ERROR: location argument cannot be empty, cannot continue init of service:vdc!vdc4yves04 ((type:input.error)
```

So far so good :-)

Problem is that the vdc4yves04 service is created anyhow, and is visible in the Cockpit Portal,  not allowing us to simply correct the problem by adding the location attribute, and again trying to execute the blueprint.

So in case an attribute is missing, or anything less goes wrong the (vdc) service should not be created...
