### ISSUE TITLE
ays fs

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#706]
depends on cuisine for
- btrfs
- rsync
- ftp
- zerotier

![image](https://cloud.githubusercontent.com/assets/6021844/21793479/370b8ab8-d70b-11e6-82ae-4da644f45b1f.png)

**Comment by rkhamis** [comment]
Using the zerotier networking in dockers defined in https://github.com/Jumpscale/jumpscale_core8/issues/710, ftp-based storage pool nodes will be used as a non-complex stor.

AYS blueprint will manage the installation, monitoring and replication to AYSFS backup nodes (communication over zerotier).

**Comment by abdulrahmantkhalifa** [comment]
pool deployed using the following blueprint 
```yaml
# connection to the g8 where to deploy 
g8client__be:
    url: 'be-scale-3.demo.greenitglobe.com'
    login: 'userlogin'
    password: 'password'


# create the vdc that will contain the vm
vdc__tweaker_cloudspace:
    description: 'storage pool vdc'
    g8client: 'be'
    account: 'account'
    location: 'be-scale-3'
    uservdc:
        - 'userlogin'

sshkey__vagrant_install:


disk.ovc__disk1vm1:
  size: 5

# create the host vm
node.ovc__nodevm1:
    bootdisk.size: 50
    memory: 2
    os.image: 'Ubuntu 16.04 x64'
    disk: ['disk1vm1']
    ports:
        - '2209:22'
        - '8201:80'
        - '2122:21'
    vdc: 'tweaker_cloudspace'
    sshkey: 'vagrant_install'


network.zerotier__gigstorage:
    id: '8056c2e21c000001'

zerotier_daemon__ztrvm1:
    os: 'nodevm1'
    networks: ['gigstorage']


fs.btrfs__fsvm1:
    os: 'nodevm1'
    mount: '/mnt/storage/'

# ftp configuration
ftp_space__space1vm1:
    path: '/mnt/storage/pool1'
    authorized_users:
        - 'gig:mysecret'
        - 'root:othersecret'
    permission: 'elrmw'

ftp__ftpvm1:
    os: 'nodevm1'
    fs: 'fsvm1'    
    spaces:
        - 'space1vm1'


disk.ovc__disk1vm2:
  size: 5

# create the host vm
node.ovc__nodevm2:
    bootdisk.size: 50
    memory: 2
    disk: ['disk1vm2']
    os.image: 'Ubuntu 16.04 x64'
    ports:
        - '2208:22'
        - '8202:80'
        - '2123:21'
    vdc: 'tweaker_cloudspace'
    sshkey: 'vagrant_install'



network.zerotier__gigstorage:
    id: '8056c2e21c000001'

zerotier_daemon__ztrvm2:
    os: 'nodevm2'
    networks: ['gigstorage']


fs.btrfs__fsvm2:
    os: 'nodevm2'
    mount: '/mnt/storage/'

# ftp configuration
ftp_space__space1vm2:
    path: '/mnt/storage/pool2'
    authorized_users:
        - 'gig:mysecret'
        - 'root:othersecret'
    permission: 'elrmw'

ftp__ftpvm2:
    os: 'nodevm2'
    fs: 'fsvm2'
    spaces:
        - 'storage1'

storage_pool__pool2:
    replicate: false
    snapshot: false    
    path: 'pool2'
    fs: 'fsvm2'
    os: 'nodevm2'

storage_pool__pool1:
    path: 'pool1'
    fs: 'fsvm1'
    os: 'nodevm1'
    pools: ['pool2']



actions:
    - action: 'install'
    - actor: 'storage_pool'
      action: 'snapshot'
      recurring: '1h'
    - actor: 'storage_pool'
      action: 'replicate'
      recurring: '1h'

```
