### ISSUE TITLE
validate docker/zerotier/ays works

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#710]
requirement
- from ays, launch docker containers 
- docker containers in zerotier & in pub network so we can create e.g. a loadbalanced caddy

**Comment by rkhamis** [comment]
@iwanbk What's the status here?

**Comment by iwanbk** [comment]
i still didn't have chance to work on this, maybe next week...

**Comment by iwanbk** [comment]
@rkhamis @zaibon 
we can have zerotier daemon running on the host and then do port forwarding to docker containers.

To do port forwarding use `-p` option as usual, with the zerotier IP, example:

```
-p ZEROTIER_IP:9000:80
```

**Comment by iwanbk** [comment]
i have tested that port forwarding also work with zerotier. We don't need to specify the zerotier ip

My test steps:

Create this blueprint
```
sshkey__vagrant_install:

node.physical__vagrant4:
  ip.public: '192.168.1.8'
  ssh.login: 'root'
  ssh.password: 'gig1234'
  sshkey: 'vagrant_install'
  ssh.addr: 'localhost'
  ssh.port: 22  


os.ssh.ubuntu__vagrant4:
  ssh.addr: '192.168.1.8'
  ssh.port: 22
  sshkey: 'vagrant_install'
  node: 'vagrant4'

node.docker__ubuntutest:
  sshkey: 'vagrant_install'
  image: 'jumpscale/ubuntu1604'
  os: 'vagrant4'
  ssh.login: 'root'
  ssh.password: 'gig1234'
  ports:
      - "80:2015"

os.ssh.ubuntu__docker_vagrant4:
  sshkey: 'vagrant_install'
  node: 'ubuntutest'

actions:
    - action: 'install'
```

execute commands:
```
ays blueprint && ays run
```

Login to the docker we just created
```
docker exec -it ubuntutest bash
```
and start file server that listen on port 2015.

from broswer, access http://zero.ti.er.ip
